// R147 P1: extracted verbatim from App.tsx module scope (parameter metadata).

// Human-readable parameter metadata — labels pulled from i18n in render
export const PARAM_META: Record<string, { labelKey: string; min: number; max: number; step: number; unit?: string }> = {
  speed:       { labelKey: 'Speed',       min: 0,    max: 2,    step: 0.05, unit: '×' },
  spread:      { labelKey: 'Spread',      min: 0,    max: 3,    step: 0.1,  unit: '×' },
  width:       { labelKey: 'Width',       min: 0,    max: 1,    step: 0.05 },
  saturation:  { labelKey: 'Saturation',  min: 0,    max: 2,    step: 0.05, unit: '×' },
  contrast:    { labelKey: 'Contrast',    min: 0,    max: 2,    step: 0.05, unit: '×' },
  intensity:   { labelKey: 'Intensity',   min: 0,    max: 1,    step: 0.05 },
  density:     { labelKey: 'Density',     min: 0,    max: 1,    step: 0.05 },
  frequency:   { labelKey: 'Rings',       min: 1,    max: 10,   step: 0.5 },
  tail:        { labelKey: 'Tail',        min: 0.05, max: 0.95, step: 0.05 },
  hueShift:    { labelKey: 'Hue Shift',   min: -180, max: 180,  step: 5,    unit: '°' },
  sensitivity: { labelKey: 'Sensitivity', min: 0.2,  max: 3,    step: 0.1,  unit: '×' },
  angle:       { labelKey: 'param.angle', min: 0,    max: 360,  step: 5,    unit: '°' },
  baseBrightness: { labelKey: 'Base Light', min: 0,    max: 1,    step: 0.05 },
  pulseAmplitude: { labelKey: 'Pulse Depth', min: 0,   max: 1,    step: 0.05 },
  phaseOffset:    { labelKey: 'Phase',      min: 0,    max: 1,    step: 0.05 },
  curtainHeight:  { labelKey: 'Curtain',    min: 0.4,  max: 1.6,  step: 0.05, unit: '×' },
  ribbonFrequency:{ labelKey: 'Ribbons',    min: 0.5,  max: 2.5,  step: 0.05, unit: '×' },
  shimmerIntensity:{ labelKey: 'Shimmer',   min: 0,    max: 1,    step: 0.05 },
  baseHue:        { labelKey: 'Base Hue',   min: 0,    max: 360,  step: 5,    unit: '°' },
  colorSpread:    { labelKey: 'Color Spread', min: 20, max: 180,  step: 5,    unit: '°' },
  softEdge:       { labelKey: 'Soft Edge',   min: 0.25, max: 1.25, step: 0.05, unit: '×' },
  heat:           { labelKey: 'Heat',        min: 0.3,  max: 1.5,  step: 0.05, unit: '×' },
  sparks:         { labelKey: 'Sparks',      min: 0,    max: 1,    step: 0.05 },
  wind:           { labelKey: 'Wind',        min: -1,   max: 1,    step: 0.05 },
  baseHeight:     { labelKey: 'Base Height', min: 0.6,  max: 1.5,  step: 0.05, unit: '×' },
  gridDensity:       { labelKey: 'param.gridDensity',       min: 0,   max: 1,   step: 0.05 },
  scanSpeed:         { labelKey: 'param.scanSpeed',         min: 0.1, max: 3,   step: 0.05, unit: '×' },
  particleIntensity: { labelKey: 'param.particleIntensity', min: 0,   max: 2,   step: 0.05, unit: '×' },
  glitchAmount:      { labelKey: 'param.glitchAmount',      min: 0,   max: 1,   step: 0.05 },
  flickerAmount:     { labelKey: 'param.flickerAmount',     min: 0,   max: 1,   step: 0.05 },
  hologramDepth:     { labelKey: 'param.hologramDepth',     min: 0,   max: 1,   step: 0.05 },
  scanWidth:         { labelKey: 'param.scanWidth',         min: 0,   max: 1,   step: 0.05 },
  // Static text params
  textX:       { labelKey: 'param.textX',    min: 0,   max: 1,   step: 0.05 },
  textY:       { labelKey: 'param.textY',    min: 0,   max: 1,   step: 0.05 },
  textScale:   { labelKey: 'param.textScale', min: 1,  max: 4,   step: 1 },
  textWeight:  { labelKey: 'param.textWeight', min: 100, max: 900, step: 100 },
}
